version: '3.7'
services:

  nginx:
    image: 'nginx:1.17-alpine'
    volumes:
      - './backend/:/var/www/html'
      - './docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
      - './log/nginx/:/var/log/nginx'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params'
      - './docker/nginx/sites/:/etc/nginx/sites'
      - './docker/nginx/snippets/:/etc/nginx/snippets'
    depends_on:
      - php
    networks:
      - backend
      - frontend
    ports:
      - '80:80'
      - '443:443'

  php:
    build:
      context: ./docker/php
      network: host
    volumes:
      - './backend/:/var/www/html'
    environment:
      docker: 'true'
    networks:
      - backend
    ports:
      - '9000:9000'

  postgres:
    image: 'postgres:12'
    volumes:
      - './backend/:/var/www/html'
      - './docker/postgres/initdb.d/:/docker-entrypoint-initdb.d'
      # - './docker/postgres/pgdata/:/var/lib/postgresql/data'
    environment:
      ICR_DB: svarta
      POSTGRES_PASSWORD: svarta
      # PGDATA: /var/lib/postgresql/data
    networks:
      - backend
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    depends_on:
      - postgres
    networks:
      - backend
    ports:
      - '8080:8080'

networks:
  backend:
  frontend:
